from numpy._core import function_base
import numpy as np
import json
import os
import sys
sys.stdout.reconfigure(encoding='utf-8')

vocab_size = 10
embedding_dim = 4
np.random.seed(42) # for reproducibility
embedding_matrix = np.random.randn(vocab_size, embedding_dim)

vocab = {
    "I": 0,
    "love": 1,
    "AI": 2,
    "cats": 3,
    "dogs": 4,
    "dog":5,
    "chased":6,
    "the":7,
    "The":8,
    "cat":9
}

sentence = "The dog chased the cat"
words = sentence.split()
seq_len=len(words)
token_ids = [vocab[word] for word in words]
embeddings = embedding_matrix[token_ids] # shape [3, 4]

#all the weights are random ,taking the embedding dimension and the embedding dimension
W_Q = np.random.randn(embedding_dim, embedding_dim)
W_K = np.random.randn(embedding_dim, embedding_dim)
W_V = np.random.randn(embedding_dim, embedding_dim)


Q = np.dot(embeddings, W_Q)
K = np.dot(embeddings, W_K)
V = np.dot(embeddings, W_V)

raw_scores_matrix = np.dot(Q, K.T)
scaled_scores_matrix = raw_scores_matrix/np.sqrt(embedding_dim)
casual_mask=np.tril(np.ones((seq_len,seq_len)))

mask_grid = np.where(casual_mask==1.0 ,0.0,-np.inf)
#add the mask grid to the scaled scores
#this forces the future positions to be - infinity
masked_score=scaled_scores_matrix+mask_grid

max_scores = np.max(masked_score,axis=1,keepdims=True)
max_scores[max_scores==-np.inf]=0.0
exp_scores = np.exp(masked_score-max_scores)
attention_weights_matrix=exp_scores/np.sum(exp_scores,axis=1,keepdims=True)


print("Sentence:", sentence)
print("Token IDs:", token_ids)
print("Embeddings shape:", embeddings.shape)
print("="*50)
print("scaled results",scaled_scores_matrix)
print("mask grid",masked_score)
print("masked result",max_scores)

attention_results = []
for i, target_word in enumerate(words):
    raw_scores = raw_scores_matrix[i]
    scaled_scores = scaled_scores_matrix[i]
    masked_scores = masked_score[i]
    weights = attention_weights_matrix[i]

    # Context vector is generated by applying weights directly to the VALUE vectors (V)
    # Shape: [3] -> [3, 1] broadcasted against [3, 4], summed over tokens to give [4]
    context = np.sum(V * weights[:, None], axis=0)

    attention_results.append({
        "target_word": target_word,
        "raw_scores": raw_scores.tolist(),
        "scaled_scores": scaled_scores.tolist(),
        "masked_scores": masked_scores.tolist(),
        "attention_weights": weights.tolist(),
        "context_vector": context.tolist()
    })
results = {
    "sentence": sentence,
    "token_ids": token_ids,
    "embeddings": embeddings.tolist(),
    "attention_results": attention_results
}

# Save to JSON
output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "results", "lab_003_attention")
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, "casual_attention.json")

with open(output_file, "w") as f:
    json.dump(results, f, indent=2)

# Print nicely
for r in results["attention_results"]:
    print(f"=== Encoding: {r['target_word']} ===")
    print("Raw Scores: ", np.round(r["raw_scores"], 3))
    print("Norm Weights: ", np.round(r["attention_weights"], 3))
    print("Context Vector: ", np.round(r["context_vector"], 4))
    print()
print("=== Causal Attention Weights Matrix ===")
print("          ", "   ".join([f"{w:6}" for w in words]))
for i, row in enumerate(attention_weights_matrix):
    row_str = "   ".join([f"{val:6.2%}" for val in row])
    print(f"{words[i]:8} | {row_str}")

def print_attention_heatmap(words, attention_matrix):
    print("\n=== Attention Heatmap ===")
    header = f"{'':<10}"
    for word in words:
        header += f"{word:<8}"
    print(header)
    print()

    for i, row_word in enumerate(words):
        row_str = f"{row_word:<10}"
        for j, col_word in enumerate(words):
            weight = attention_matrix[i][j]
            if weight >= 0.70:
                block = "███"
            elif weight >= 0.20:
                block = "▓"
            elif weight >= 0.01:
                block = "░"
            else:
                block = "   "
            row_str += f"{block:<8}"
        print(row_str)
        print()

print_attention_heatmap(words, attention_weights_matrix)
print(f"Results saved to {os.path.relpath(output_file)}")