from numpy._typing import _nested_sequence
from numpy._typing import _nested_sequence
from numpy._core import function_base
import numpy as np
import json
import os
import sys
sys.stdout.reconfigure(encoding='utf-8')

vocab = {
    "i": 0,
    "love": 1,
    "ai": 2,
    "cats": 3,
    "dogs": 4,
    "dog": 5,
    "chased": 6,
    "the": 7,
    "cat": 8,
    "automated": 9,
    "agent": 10,
    "quickly": 11,
    "executed": 12,
    "server": 13,
    "backup": 14,
    "script": 15,
    "because": 16,
    "it": 17,
    "noticed": 18,
    "a": 19,
    "memory": 20,
    "leak": 21,
    "The":22,
    "code":23,
    "compiles":24,
    "correctly":25
}
vocab_size = len(vocab)
embedding_dim = 8
np.random.seed(42) # for reproducibility
embedding_matrix = np.random.randn(vocab_size, embedding_dim)

sentence = "code compiles correctly"
words = sentence.split()
seq_len=len(words)
token_ids = [vocab[word] for word in words]
embeddings = embedding_matrix[token_ids] # shape [3, 4]

n_heads = 4
head_dimension = embedding_dim// n_heads



#all the weights are random ,taking the embedding dimension and the embedding dimension
W_Q = np.random.randn(embedding_dim, embedding_dim)
W_K = np.random.randn(embedding_dim, embedding_dim)
W_V = np.random.randn(embedding_dim, embedding_dim)

#multi head attention
Q_base = np.dot(embeddings, W_Q)
K_base = np.dot(embeddings, W_K)
V_base = np.dot(embeddings, W_V)

Q_split = Q_base.reshape(seq_len, n_heads, head_dimension)
K_split = K_base.reshape(seq_len, n_heads, head_dimension)
V_split = V_base.reshape(seq_len, n_heads, head_dimension)

Q = Q_split.transpose(1, 0, 2)
K = K_split.transpose(1, 0, 2)
K_T=K_split.transpose(1,2,0)
V = V_split.transpose(1, 0, 2)


raw_scores_matrix = np.matmul(Q, K_T)
scaled_scores_matrix = raw_scores_matrix/np.sqrt(head_dimension)
casual_mask=np.tril(np.ones((seq_len,seq_len)))

mask_grid = np.where(casual_mask==1.0 ,0.0,-np.inf)
#add the mask grid to the scaled scores
#this forces the future positions to be - infinity
masked_score=scaled_scores_matrix + mask_grid[ None, :, :]

max_scores = np.max(masked_score,axis=1,keepdims=True)
max_scores[max_scores==-np.inf]=0.0
exp_scores = np.exp(masked_score-max_scores)
attention_weights_matrix=exp_scores/np.sum(exp_scores,axis=-1,keepdims=True)

out_heads = np.matmul(attention_weights_matrix,V)
out_transported = out_heads.transpose(1,0,2)

multi_head_output=out_transported.reshape(seq_len , embedding_dim)

print("Sentence:", sentence)
print("Token IDs:", token_ids)
print("Embeddings shape:", embeddings.shape)
print("="*50)
print("scaled results",scaled_scores_matrix)
print("mask grid",masked_score)
print("masked result",max_scores)
print("multi Head output",multi_head_output)
print("Success! Final output shape:",multi_head_output.shape)
attention_results = []
for i, target_word in enumerate(words):
    raw_scores = raw_scores_matrix[:, i, :]
    scaled_scores = scaled_scores_matrix[:, i, :]
    masked_scores = masked_score[:, i, :]
    weights = attention_weights_matrix[:, i, :]

    # Context vector is generated by applying weights directly to the VALUE vectors (V)
    # Shape: [3] -> [3, 1] broadcasted against [3, 4], summed over tokens to give [4]
    context = np.sum(V * weights[:,:, None], axis=1)

    attention_results.append({
        "target_word": target_word,
        "raw_scores": raw_scores.tolist(),
        "scaled_scores": scaled_scores.tolist(),
        "masked_scores": masked_scores.tolist(),
        "multi_head_output":multi_head_output.tolist(),
        "attention_weights": weights.tolist(),
        "context_vector": context.tolist()
    })
results = {
    "sentence": sentence,
    "token_ids": token_ids,
    "embeddings": embeddings.tolist(),
    "attention_results": attention_results
}

# Save to JSON
output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "results", "lab_003_attention")
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, "multiHead_attention.json")

with open(output_file, "w") as f:
    json.dump(results, f, indent=2)

# Print nicely
for r in results["attention_results"]:
    print(f"=== Encoding: {r['target_word']} ===")
    print("Raw Scores: ", np.round(r["raw_scores"], 3))
    print("Norm Weights: ", np.round(r["attention_weights"], 3))
    print("Context Vector: ", np.round(r["context_vector"], 4))
    print()
print("=== Causal Attention Weights Matrix ===")
print("          ", "   ".join([f"{w:6}" for w in words]))


for head_idx in range(n_heads):
    print(f"--- Head {head_idx} Attention Weights ---")
    head_weights = weights[head_idx] # Pulls a 1D array of 15 numbers

    # This will now work perfectly because 'val' is a single float number
    row_str = "   ".join([f"{val:9.2%}" for val in head_weights])
    print(row_str)

def print_attention_heatmap(words, attention_matrix):
    # Determine how many heads are in the matrix (Axis 0)
    n_heads = attention_matrix.shape[0]

    for head_idx in range(n_heads):
        print(f"\n===== ATTENTION HEAD {head_idx} HEATMAP =====")

        # Header Row for Columns
        header = f"{'':<10}" + "".join([f"{w:<8}" for w in words])
        print(header)
        print("-" * len(header))

        for i, row_word in enumerate(words):
            row_str = f"{row_word:<10}"
            for j, col_word in enumerate(words):

                # FIX: Index into the specific head_idx at Axis 0
                weight = attention_matrix[head_idx][i][j]

                if weight >= 0.70:
                    block = "███"
                elif weight >= 0.20:
                    block = "▓"
                elif weight >= 0.01:
                    block = "░"
                else:
                    block = "   "
                row_str += f"{block:<8}"
            print(row_str)
print_attention_heatmap(words, attention_weights_matrix)
print(f"Results saved to {os.path.relpath(output_file)}")