import numpy as np
import json
import os

vocab_size = 5
embedding_dim = 4
np.random.seed(42) # for reproducibility
embedding_matrix = np.random.randn(vocab_size, embedding_dim)

vocab = {
    "I": 0,
    "love": 1,
    "AI": 2,
    "cats": 3,
    "dogs": 4
}

sentence = "I love dogs"
words = sentence.split()
token_ids = [vocab[word] for word in words]
embeddings = embedding_matrix[token_ids] # shape [3, 4]

#all the weights are random ,taking the embedding dimension and the embedding dimension
W_Q = np.random.randn(embedding_dim, embedding_dim)
W_K = np.random.randn(embedding_dim, embedding_dim)
W_V = np.random.randn(embedding_dim, embedding_dim)


Q = np.dot(embeddings, W_Q)
K = np.dot(embeddings, W_K)
V = np.dot(embeddings, W_V)

raw_scores_matrix = np.dot(Q, K.T)
scaled_scores_matrix = raw_scores_matrix/np.sqrt(embedding_dim)

exp_scores = np.exp(scaled_scores_matrix-np.max(scaled_scores_matrix,axis=1,keepdims=True))
attention_weights_matrix=exp_scores/np.sum(exp_scores,axis=1,keepdims=True)


print("Sentence:", sentence)
print("Token IDs:", token_ids)
print("Embeddings shape:", embeddings.shape)
print("="*50)

attention_results = []
for i, target_word in enumerate(words):
    raw_scores = scaled_scores_matrix[i]
    weights = attention_weights_matrix[i]

    # Context vector is generated by applying weights directly to the VALUE vectors (V)
    # Shape: [3] -> [3, 1] broadcasted against [3, 4], summed over tokens to give [4]
    context = np.sum(V * weights[:, None], axis=0)

    attention_results.append({
        "target_word": target_word,
        "raw_scores": raw_scores.tolist(),
        "attention_weights": weights.tolist(),
        "context_vector": context.tolist()
    })
results = {
    "sentence": sentence,
    "token_ids": token_ids,
    "embeddings": embeddings.tolist(),
    "attention_results": attention_results
}

# Save to JSON
output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "results", "lab_003_attention")
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, "manual_attention.json")

with open(output_file, "w") as f:
    json.dump(results, f, indent=2)

# Print nicely
for r in results["attention_results"]:
    print(f"=== Encoding: {r['target_word']} ===")
    print("Raw Scores: ", np.round(r["raw_scores"], 3))
    print("Norm Weights: ", np.round(r["attention_weights"], 3))
    print("Context Vector: ", np.round(r["context_vector"], 4))
    print()

print(f"Results saved to {os.path.relpath(output_file)}")